name: sqflite_example
description: Demonstrates how to use the sqflite plugin.
publish_to: none
version: '0.2.0'

environment:
  sdk: ">=2.7.0-dev <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  path: any
  collection: any
  flutter:
    sdk: flutter
  sqflite:
    git:
      url: git://github.com/tekartik/sqflite
      path: sqflite


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.1
  test:
  matcher: '>=0.12.3 < 2.0.0'
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.10.0'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/example.db
    - assets/issue_64.db

dependency_overrides:
  sqflite:
    path: ../