name: sqflite_darwin
repository: https://github.com/tekartik/sqflite/tree/master/sqflite_darwin
issue_tracker: https://github.com/tekartik/sqflite/issues
description: iOS/MacOS flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine.
version: 2.4.2

# This package supports all platforms listed below.
platforms:
  ios:
  macos:

topics:
  - sql
  - database

funding:
  - https://github.com/sponsors/alextekartik

environment:
  sdk: ^3.9.0
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SqflitePlugin
        dartPluginClass: SqfliteDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: SqflitePlugin
        dartPluginClass: SqfliteDarwin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  sqflite_platform_interface: '>=2.4.0-0 <4.0.0'
  meta: '>=1.7.0 <3.0.0'
  sqflite_common: '>=2.5.4+5 <4.0.0'
  path: '>=1.8.0 <3.0.0'

dev_dependencies:
  flutter_lints: ">=5.0.0"
  process_run: '>=1.2.0'
  http: '>=1.0.0'
  flutter_test:
    sdk: flutter
  test_api: '>=0.2.19'
  pub_semver: '>=2.0.0'
