name: sqflite_common_test
description: SQFlite test package
version: 0.5.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  sqflite_common_ffi: '>=2.2.0-dev.5 <4.0.0'
  sqflite_common: '>=2.4.1-1 <4.0.0'
  test:
  path:
  synchronized:
dev_dependencies:
  process_run: '>=0.11.0+2'

  lints: '>=1.0.1'

dependency_overrides:
  sqflite_common:
    path: ../sqflite_common
  sqflite_common_ffi:
    path: ../sqflite_common_ffi
