name: sqflite_common
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_common
description: Dart wrapper on SQLite, a self-contained, high-reliability, embedded, SQL database engine.
version: 2.5.5
funding:
  - https://github.com/sponsors/alextekartik

environment:
  sdk: ^3.7.0

dependencies:
  synchronized: ">=3.0.0 <5.0.0"
  path: ">=1.8.0 <3.0.0"
  meta: ">=1.14.0 <3.0.0"

dev_dependencies:
  lints: ">=4.0.0"
  process_run: ">=1.1.0"
  http: ">=1.2.2"
  test: ">=1.25.8"
  test_api: ">=0.7.3"
  pub_semver: ">=2.1.4"
