name: sqflite_repo
description: Sqflite repo
version: 0.1.0
homepage: https://github.com/tekartik/sqflite
publish_to: none

environment:
  sdk: '>=2.4.0-dev <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: dart2
    version: '>=0.1.0'
  process_run: '>=0.10.6'

dependency_overrides:
  pedantic: '>=1.9.0 <3.0.0'
