name: sqflite
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/sqflite
description: Flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine.
version: 0.7.1

environment:
  sdk: ">=1.24.0 <2.0.0"

flutter:
  plugin:
    androidPackage: com.tekartik.sqflite
    pluginClass: SqflitePlugin

dependencies:
  flutter:
    sdk: flutter
  synchronized: '>=1.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

