name: sqflite
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite
description: Flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine.
version: 1.3.1

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.10.1 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.tekartik.sqflite
        pluginClass: SqflitePlugin
      ios:
        pluginClass: SqflitePlugin
      macos:
        pluginClass: SqflitePlugin


dependencies:
  flutter:
    sdk: flutter
  sqflite_common: '>=1.0.2+1 <3.0.0'
  path: '>=1.5.1 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.10.7'
  http: '>=0.12.0+2'
  flutter_test:
    sdk: flutter
  test_api:
