name: sqflite
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/sqflite
description: Flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine.
version: 1.1.6+5

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: ">=1.2.1 <2.0.0"

flutter:
  plugin:
    androidPackage: com.tekartik.sqflite
    pluginClass: SqflitePlugin

dependencies:
  flutter:
    sdk: flutter
  synchronized: '>=2.0.2 <4.0.0'
  path: '>=1.5.1 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.10.0'
  flutter_test:
    sdk: flutter
  test_api: