name: sqflite
repository: https://github.com/tekartik/sqflite/tree/master/sqflite
issue_tracker: https://github.com/tekartik/sqflite/issues
description: Flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine.
version: 2.4.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:

topics:
  - sql
  - database

funding:
  - https://github.com/sponsors/alextekartik

environment:
  sdk: ^3.5.0
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: sqflite_android
      ios:
        default_package: sqflite_darwin
      macos:
        default_package: sqflite_darwin

dependencies:
  flutter:
    sdk: flutter
  sqflite_android: ">=2.4.0-1 <4.0.0"
  sqflite_darwin: ">=2.4.1-0 <4.0.0"
  sqflite_platform_interface: ">=2.4.0-0 <4.0.0"
  sqflite_common: ">=2.5.0-1 <4.0.0"
  path: ">=1.8.0 <3.0.0"

dev_dependencies:
  flutter_lints: ">=5.0.0"
  process_run: ">=0.12.0"
  http: ">=0.13.0"
  flutter_test:
    sdk: flutter
  test_api: ">=0.2.19"
  pub_semver: ">=2.0.0"
