name: sqflite_common_ffi_async_test
description: Test for sqflite_common_ffi_async
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  sqflite_common_ffi_async:
    path: ../sqflite_common_ffi_async
  sqflite_common_test:
    git:
      url: https://github.com/tekartik/sqflite
      ref: dart3a
      path: sqflite_common_test
    version: '>=0.3.0'
  test: '>=1.21.0'

dev_dependencies:
  lints: '>=2.0.0'

dependency_overrides:
  sqflite_common_test:
    path: ../../sqflite_common_test
  sqflite_common_ffi_async:
    path: ../sqflite_common_ffi_async
  sqflite_common:
    path: ../../sqflite_common
  sqflite_common_ffi:
    path: ../../sqflite_common_ffi