name: sqflite_common_ffi
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi
description: sqflite ffi based implementation, for desktop and units tests.
version: 2.1.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sqlite3: '>=1.0.0 <3.0.0'
  sqflite_common: '>=2.0.1 <4.0.0'
  synchronized: '>=3.0.0 <5.0.0'
  path: '>=1.8.0 <3.0.0'
  meta: '>=1.3.0 <3.0.0'

dev_dependencies:
  lints:
  test: '>=1.16.2'
  process_run: '>=0.12.0'
  pub_semver: '>=2.0.0'

