name: sqflite_common_ffi
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi
description: sqflite ffi based implementation, for desktop and units tests.
version: 2.3.5
funding:
  - https://github.com/sponsors/alextekartik

# This package supports all platforms listed below.
platforms:
  linux:
  macos:
  windows:
  android:
  ios:
  web:

topics:
  - sql
  - database

environment:
  sdk: ^3.7.0

dependencies:
  sqlite3: '>=2.3.0 <4.0.0'
  sqflite_common: '>=2.5.4+2 <4.0.0'
  synchronized: '>=3.0.0 <5.0.0'
  path: '>=1.8.0 <3.0.0'
  meta: '>=1.3.0 <3.0.0'

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  process_run: '>=1.2.0'
  pub_semver: '>=2.0.0'
  archive: '>=4.0.0'
  http:
