name: sqflite_common_ffi
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi
description: sqflite ffi based implementation, for desktop and units tests.
version: 2.0.0-nullsafety.6

environment:
  sdk: '>=2.12.0-29 <3.0.0'

dependencies:
  sqlite3: '>=0.1.9-nullsafety.0 <1.0.0'
  sqflite_common: '>=2.0.0-nullsafety.2 <3.0.0'
  synchronized: '>=3.0.0-nullsafety.0 <4.0.0'
  path: '>=1.8.0-nullsafety.3 <3.0.0'
  meta: '>=1.3.0-nullsafety.6 <3.0.0'

dev_dependencies:
  pedantic: '>=1.10.0-nullsafety.3'
  test: '>=1.16.0-nullsafety.10'
  process_run: '>=0.11.0+2'
  pub_semver:

