name: sqflite_common_ffi
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi
description: sqflite ffi based implementation, for desktop and units tests.
version: 1.1.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  sqlite3: '>=0.1.4 <1.0.0'
  sqflite_common: '>=1.0.1 <3.0.0'
  synchronized: '>=2.0.2 <4.0.0'
  path: '>=1.5.1 <3.0.0'
  meta: '>=1.1.8 <3.0.0'

dev_dependencies:
  pedantic:
  test:
  process_run: '>=0.10.7'
