name: sqflite_common_ffi_async
homepage: https://github.com/tekartik/sqflite/tree/master/packages/sqflite_common_ffi_async
description: Sqflite API on top on sqlite_async from PowerSync, ffi based implementation.
version: 0.1.4

# This package supports all platforms listed below.
platforms:
  linux:
  macos:
  windows:
  android:
  ios:

environment:
  sdk: ^3.7.0

dependencies:
  path: '>=1.8.0 <3.0.0'
  sqflite_common: '>=2.5.4 <4.0.0'
  sqflite_common_ffi: '>=2.3.3 <4.0.0'
  sqlite_async: '>=0.6.0 <2.0.0'

dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
