name: sqflite_common_ffi_web
repository: https://github.com/tekartik/sqflite/tree/master/packages_web/sqflite_common_ffi_web
description: Sqflite web implementation using sqlite3 ffi and sqlite3 wasm.
version: 0.3.2
funding:
  - https://github.com/sponsors/alextekartik

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  path: '>=1.7.0 <3.0.0'
  sqflite_common_ffi: '>=2.2.1 <4.0.0'
  sqflite_common: '>=2.4.1 <4.0.0'
  sqlite3: '>=1.9.0 <3.0.0'
  http: '>=0.13.4 <2.0.0'
  js: '>=0.6.4 <2.0.0'
  synchronized: '>=3.0.0+3 <5.0.0'
  process_run: '>=0.12.3+2 <2.0.0'
  dev_test: '>=0.15.5+1 <2.0.0'
  pub_semver: '>=2.1.2 <4.0.0'
  io: '>=1.0.3 <3.0.0'
  args: '>=2.3.1 <4.0.0'
  meta: '>=1.8.0 <3.0.0'
dev_dependencies:
  test:
  build_runner: '>=2.1.4 <4.0.0'
  build_web_compilers: '>=3.2.1 <5.0.0'
  lints: '>=2.0.0 <4.0.0'

# dependency_overrides:
#  sqflite_common_ffi:
#    path: ../../sqflite_common_ffi
#  sqflite_common:
#    path: ../../sqflite_common

executables:
  setup: